package com.bplow.netconn.newcms.domain;
// default package
// Generated 2015-7-5 19:49:47 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FmCatalogId generated by hbm2java
 */
public class FmCatalog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8832592145257980858L;
	
	private String catalogId;
	private String catalogName;
	private String catalogDesc;
	private String secondName;
	private String imageSrc;
	private Integer orderId;
	private Date operateDate;
	private Character isDeleteFlag;
	private String catalogType;
	private String parentCatalogId;

	public FmCatalog() {
	}

	public FmCatalog(String catalogId, String catalogName,
			String catalogDesc, String secondName, String imageSrc,
			Integer orderId, Date operateDate, Character isDeleteFlag,
			String catalogType, String parentCatalogId) {
		this.catalogId = catalogId;
		this.catalogName = catalogName;
		this.catalogDesc = catalogDesc;
		this.secondName = secondName;
		this.imageSrc = imageSrc;
		this.orderId = orderId;
		this.operateDate = operateDate;
		this.isDeleteFlag = isDeleteFlag;
		this.catalogType = catalogType;
		this.parentCatalogId = parentCatalogId;
	}

	public String getCatalogId() {
		return this.catalogId;
	}

	public void setCatalogId(String catalogId) {
		this.catalogId = catalogId;
	}

	public String getCatalogName() {
		return this.catalogName;
	}

	public void setCatalogName(String catalogName) {
		this.catalogName = catalogName;
	}

	public String getCatalogDesc() {
		return this.catalogDesc;
	}

	public void setCatalogDesc(String catalogDesc) {
		this.catalogDesc = catalogDesc;
	}

	public String getSecondName() {
		return this.secondName;
	}

	public void setSecondName(String secondName) {
		this.secondName = secondName;
	}

	public String getImageSrc() {
		return this.imageSrc;
	}

	public void setImageSrc(String imageSrc) {
		this.imageSrc = imageSrc;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public Date getOperateDate() {
		return this.operateDate;
	}

	public void setOperateDate(Date operateDate) {
		this.operateDate = operateDate;
	}

	public Character getIsDeleteFlag() {
		return this.isDeleteFlag;
	}

	public void setIsDeleteFlag(Character isDeleteFlag) {
		this.isDeleteFlag = isDeleteFlag;
	}

	public String getCatalogType() {
		return this.catalogType;
	}

	public void setCatalogType(String catalogType) {
		this.catalogType = catalogType;
	}

	public String getParentCatalogId() {
		return this.parentCatalogId;
	}

	public void setParentCatalogId(String parentCatalogId) {
		this.parentCatalogId = parentCatalogId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FmCatalog))
			return false;
		FmCatalog castOther = (FmCatalog) other;

		return ((this.getCatalogId() == castOther.getCatalogId()) || (this
				.getCatalogId() != null && castOther.getCatalogId() != null && this
				.getCatalogId().equals(castOther.getCatalogId())))
				&& ((this.getCatalogName() == castOther.getCatalogName()) || (this
						.getCatalogName() != null
						&& castOther.getCatalogName() != null && this
						.getCatalogName().equals(castOther.getCatalogName())))
				&& ((this.getCatalogDesc() == castOther.getCatalogDesc()) || (this
						.getCatalogDesc() != null
						&& castOther.getCatalogDesc() != null && this
						.getCatalogDesc().equals(castOther.getCatalogDesc())))
				&& ((this.getSecondName() == castOther.getSecondName()) || (this
						.getSecondName() != null
						&& castOther.getSecondName() != null && this
						.getSecondName().equals(castOther.getSecondName())))
				&& ((this.getImageSrc() == castOther.getImageSrc()) || (this
						.getImageSrc() != null
						&& castOther.getImageSrc() != null && this
						.getImageSrc().equals(castOther.getImageSrc())))
				&& ((this.getOrderId() == castOther.getOrderId()) || (this
						.getOrderId() != null && castOther.getOrderId() != null && this
						.getOrderId().equals(castOther.getOrderId())))
				&& ((this.getOperateDate() == castOther.getOperateDate()) || (this
						.getOperateDate() != null
						&& castOther.getOperateDate() != null && this
						.getOperateDate().equals(castOther.getOperateDate())))
				&& ((this.getIsDeleteFlag() == castOther.getIsDeleteFlag()) || (this
						.getIsDeleteFlag() != null
						&& castOther.getIsDeleteFlag() != null && this
						.getIsDeleteFlag().equals(castOther.getIsDeleteFlag())))
				&& ((this.getCatalogType() == castOther.getCatalogType()) || (this
						.getCatalogType() != null
						&& castOther.getCatalogType() != null && this
						.getCatalogType().equals(castOther.getCatalogType())))
				&& ((this.getParentCatalogId() == castOther
						.getParentCatalogId()) || (this.getParentCatalogId() != null
						&& castOther.getParentCatalogId() != null && this
						.getParentCatalogId().equals(
								castOther.getParentCatalogId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCatalogId() == null ? 0 : this.getCatalogId().hashCode());
		result = 37
				* result
				+ (getCatalogName() == null ? 0 : this.getCatalogName()
						.hashCode());
		result = 37
				* result
				+ (getCatalogDesc() == null ? 0 : this.getCatalogDesc()
						.hashCode());
		result = 37
				* result
				+ (getSecondName() == null ? 0 : this.getSecondName()
						.hashCode());
		result = 37 * result
				+ (getImageSrc() == null ? 0 : this.getImageSrc().hashCode());
		result = 37 * result
				+ (getOrderId() == null ? 0 : this.getOrderId().hashCode());
		result = 37
				* result
				+ (getOperateDate() == null ? 0 : this.getOperateDate()
						.hashCode());
		result = 37
				* result
				+ (getIsDeleteFlag() == null ? 0 : this.getIsDeleteFlag()
						.hashCode());
		result = 37
				* result
				+ (getCatalogType() == null ? 0 : this.getCatalogType()
						.hashCode());
		result = 37
				* result
				+ (getParentCatalogId() == null ? 0 : this.getParentCatalogId()
						.hashCode());
		return result;
	}

}
