package com.bplow.netconn.newcms.domain;

// default package
// Generated 2015-7-5 19:49:47 by Hibernate Tools 4.0.0

/**
 * FmFreemarktmpl generated by hbm2java
 */
public class FmFreemarktmpl implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String id;
	private String tmplName;
	private String tmplCnt;

	public FmFreemarktmpl() {
	}

	public FmFreemarktmpl(String id) {
		this.id = id;
	}

	public FmFreemarktmpl(String id, String tmplName, String tmplCnt) {
		this.id = id;
		this.tmplName = tmplName;
		this.tmplCnt = tmplCnt;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getTmplName() {
		return this.tmplName;
	}

	public void setTmplName(String tmplName) {
		this.tmplName = tmplName;
	}

	public String getTmplCnt() {
		return this.tmplCnt;
	}

	public void setTmplCnt(String tmplCnt) {
		this.tmplCnt = tmplCnt;
	}

}
