package com.bplow.netconn.newcms.domain;
// default package
// Generated 2015-7-5 19:49:47 by Hibernate Tools 4.0.0

import java.util.Date;

/**
 * FmProductId generated by hbm2java
 */
public class FmProduct implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8308642778627501913L;
	private Long id;
	private String productName;
	private String catalogId;
	private String productDesc;
	private String productImageUrl;
	private Character isShow;
	private Integer orderId;
	private Date gmtCreate;
	private Date gmtModify;

	public FmProduct() {
	}

	public FmProduct(Long id, String productName, String catalogId,
			String productDesc, String productImageUrl, Character isShow,
			Integer orderId, Date gmtCreate, Date gmtModify) {
		this.id = id;
		this.productName = productName;
		this.catalogId = catalogId;
		this.productDesc = productDesc;
		this.productImageUrl = productImageUrl;
		this.isShow = isShow;
		this.orderId = orderId;
		this.gmtCreate = gmtCreate;
		this.gmtModify = gmtModify;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getCatalogId() {
		return this.catalogId;
	}

	public void setCatalogId(String catalogId) {
		this.catalogId = catalogId;
	}

	public String getProductDesc() {
		return this.productDesc;
	}

	public void setProductDesc(String productDesc) {
		this.productDesc = productDesc;
	}

	public String getProductImageUrl() {
		return this.productImageUrl;
	}

	public void setProductImageUrl(String productImageUrl) {
		this.productImageUrl = productImageUrl;
	}

	public Character getIsShow() {
		return this.isShow;
	}

	public void setIsShow(Character isShow) {
		this.isShow = isShow;
	}

	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	public Date getGmtCreate() {
		return this.gmtCreate;
	}

	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

	public Date getGmtModify() {
		return this.gmtModify;
	}

	public void setGmtModify(Date gmtModify) {
		this.gmtModify = gmtModify;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FmProduct))
			return false;
		FmProduct castOther = (FmProduct) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getProductName() == castOther.getProductName()) || (this
						.getProductName() != null
						&& castOther.getProductName() != null && this
						.getProductName().equals(castOther.getProductName())))
				&& ((this.getCatalogId() == castOther.getCatalogId()) || (this
						.getCatalogId() != null
						&& castOther.getCatalogId() != null && this
						.getCatalogId().equals(castOther.getCatalogId())))
				&& ((this.getProductDesc() == castOther.getProductDesc()) || (this
						.getProductDesc() != null
						&& castOther.getProductDesc() != null && this
						.getProductDesc().equals(castOther.getProductDesc())))
				&& ((this.getProductImageUrl() == castOther
						.getProductImageUrl()) || (this.getProductImageUrl() != null
						&& castOther.getProductImageUrl() != null && this
						.getProductImageUrl().equals(
								castOther.getProductImageUrl())))
				&& ((this.getIsShow() == castOther.getIsShow()) || (this
						.getIsShow() != null && castOther.getIsShow() != null && this
						.getIsShow().equals(castOther.getIsShow())))
				&& ((this.getOrderId() == castOther.getOrderId()) || (this
						.getOrderId() != null && castOther.getOrderId() != null && this
						.getOrderId().equals(castOther.getOrderId())))
				&& ((this.getGmtCreate() == castOther.getGmtCreate()) || (this
						.getGmtCreate() != null
						&& castOther.getGmtCreate() != null && this
						.getGmtCreate().equals(castOther.getGmtCreate())))
				&& ((this.getGmtModify() == castOther.getGmtModify()) || (this
						.getGmtModify() != null
						&& castOther.getGmtModify() != null && this
						.getGmtModify().equals(castOther.getGmtModify())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37
				* result
				+ (getProductName() == null ? 0 : this.getProductName()
						.hashCode());
		result = 37 * result
				+ (getCatalogId() == null ? 0 : this.getCatalogId().hashCode());
		result = 37
				* result
				+ (getProductDesc() == null ? 0 : this.getProductDesc()
						.hashCode());
		result = 37
				* result
				+ (getProductImageUrl() == null ? 0 : this.getProductImageUrl()
						.hashCode());
		result = 37 * result
				+ (getIsShow() == null ? 0 : this.getIsShow().hashCode());
		result = 37 * result
				+ (getOrderId() == null ? 0 : this.getOrderId().hashCode());
		result = 37 * result
				+ (getGmtCreate() == null ? 0 : this.getGmtCreate().hashCode());
		result = 37 * result
				+ (getGmtModify() == null ? 0 : this.getGmtModify().hashCode());
		return result;
	}

}
